version: '3'
services:
  web_api:
    build:
      context: ./IntercomCameraWebApi
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      PG_CONNECTION_STRING: "Server=db;Port=5432;Database=trx;User ID=postgres;Password=postgres"
  db:
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trx
